[package]
name = "cursor-cleanup"
version = "0.3.1"
edition = "2021"
description = "Interactive cleaner for VSCode / Cursor"
license = "MIT"
repository = "https://github.com/911218sky/vscode-cursor-cleanup"
readme = "README.md"

[[bin]]
name = "cursor-cleanup"
path = "src/main.rs"

[dependencies]
unicode-width = "0.2.0"
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
crossterm = "0.28"
tui-input = "0.11"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"
panic = "abort"
